### PR TITLE
Feat: Wandb logging

### PR DESCRIPTION
**Pull request by p1atdev**
I added wandb integration to monitor the training.
Loss and sample image logging are supported.

image

Example config:

```yaml
job: extension
config:
  name: "my_first_flux_lora_v1"
  process:
    - type: 'sd_trainer'
      training_folder: ...
      ... # other config
      # logging config
      logging: 
        use_wandb: true # enable wandb by this flag
        project_name: my_flux_lora_style_1 # default is "ai-toolkit"
        run_name: "first_try" # empty here to use random generated name by wandb
```

### CODE REVIEW

**Comment by p1atdev** [comment]
I have found that the logging does not follow the logging.log_every parameter, so I have to fix that.

**Comment by jaretburkett** [comment]
Thank you. I'll go through and test all of this in the next few days when I get a chance.

**Comment by robertvoy** [comment]
Does this work? Or is there a way to get a log for the loss currently?

**Comment by khronimo** [comment]
Hope this gets merged. Wandb logging would be nice to have

**Comment by davidattias** [comment]
What's the status on this one? I would to use it as well....

**Comment by WetOnTheWater** [comment]
@jaretburkett any luck on testing? Oddly enough noticed that this trainer on Replicate supports it but not officially here yet

**Comment by jaretburkett** [comment]
Sorry this took so long. Thank you @p1atdev

**Comment by davidattias** [comment]
Awesome! Thank you @jaretburkett @p1atdev

**Comment by Xqua** [comment]
> No need to fill out Wandb authentication？

You need to `pip install wandb` and then `wandb login`

**Comment by Xqua** [comment]
I can't seem to get the lr or loss to be logged in wandb ? 

its as if this 
image

does not trigger ?

**Pull request merged**
