### PR TITLE
issue #76, and RunPod cloud training setup #90

### PR DESCRIPTION
**Pull request by martintomov**
- Issue https://github.com/ostris/ai-toolkit/issues/76
- RunPod cloud training setup https://github.com/ostris/ai-toolkit/issues/90

### CODE REVIEW

**Comment by s65-dev** [comment]
huge thank you for runpod config, finally i can try this!!

**Comment by ingl6rious** [comment]
Thanks

**Comment by frailloris** [comment]
Awesome, could you make a guide for training on [modal.com](https://modal.com/)?

**Comment by jaretburkett** [comment]
Thank you

**Comment by martintomov** [comment]
> Awesome, could you make a guide for training on [modal.com](https://modal.com/)?

@frailloris  I believe the setup would be pretty much the same, but sure - I'll check it out in my free time

**Comment by martintomov** [comment]
> Awesome, could you make a guide for training on [modal.com](https://modal.com/)?

here it is. https://github.com/ostris/ai-toolkit/pull/115

**Pull request merged**
