### PR TITLE
Modal cloud training support, fixed typo in toolkit/scheduler.py, Schnell training support for Colab, issue #92 , issue #114

### PR DESCRIPTION
**Pull request by martintomov**
- Added `peft` to `requirements.txt` since it’s needed for Schnell training. #92 
- Fixed some missing parameters in the Colab notebook that were in the local config files. #114 
- Threw in `!nvidia-smi` at the top of the notebooks to make sure the GPU is being used.
- Schnell training notebook for Colab
- Fixed typo in toolkit/scheduler.py - Commit: [facor -> factor](https://github.com/martintomov/ai-toolkit/commit/c07a6be7daa18d4318e49c2255294a6d70d3ba9d#diff-0a5f4c30f723657bb986dad5cd1d6f221ceae0aea3552aafaa9bffee3f8ddfeb)
- Training on Modal cloud + setup guide in README.md

### Schnell training notebook Colab
schnell-colab

### Training on Modal
Modal Traning Screenshot

### CODE REVIEW

**Comment by ingl6rious** [comment]
where can i find the schnell training notebook?

**Comment by martintomov** [comment]
Until @jaretburkett merges, you can find it here:
https://github.com/martintomov/ai-toolkit/blob/main/notebooks/FLUX_1_schnell_LoRA_Training.ipynb

**Comment by ingl6rious** [comment]
I didn't understand at first that I need A100 gpu, but I got it working and lora is good. Thanks martin

**Comment by jaretburkett** [comment]
Excellent work! Thank you so much! You are killing it with these PRs

**Comment by martintomov** [comment]
Happy to help the project

**Comment by frailloris** [comment]
@martintomov I got it running thanks to you! Appreciate it

**Pull request merged**
